### ISSUE TITLE
Wrong dates showing up

### ISSUE THREAD

**Issue by sanyogthescholar** [sirmordred/WhatsCloud-Tracker#7] opened 2019-05-07 14:24 UTC
It is showing me wrong dates. I am seeing dates of 2020 and 2021 under most active dates. Please fix this.
Here are how the dates are shown in the exported .txt file:
4/16/19, 19:02
4/16/19, 20:54
4/23/19, 19:38

**Comment by sirmordred** [comment] 2019-05-07 21:44
Thanx so much for the feedback, marked as bug, thinking to implement dynamic switch for different date formats (like dd/mm/yyyy, mm/DD/yyyy etc.) on next version so users will be able to select their proper date format through app settings 👍

**Comment by sirmordred** [comment] 2019-05-09 07:55
Ok, released new version, it includes "date format" selector so you can choose appropriate date format through app settings, you should choose "MM/dd/yyyy" date format in your case 👍 
Let me know if the issue is fixed for you, closing it for now, you can re-open if its not fixed 👍

**Closed as completed by sirmordred** 2019-05-09 07:55 UTC
Labels: bug

**Comment by Juda404** [comment] 2019-08-09 14:26
Bug still exists, I keep on getting dates in 2020 and for large chats it chooses different dates to filter.
